name: 'Get Infisical Secrets'
description: 'Get infisical secrets and add to GitHub Actions env'
author: 'DMJoh'
branding:
  icon: 'download-cloud'
  color: 'yellow'
inputs:
  service_token:
    description: 'Infisical Service Token'
    required: true
  output_file:
    description: 'Output file path'
    required: true
    default: '.env'
  infisical_url:
    description: 'Infisical API URL'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Get the secret and write it to a file of choice
      shell: bash
      run: |
        curl --request GET \
        --url "${{ inputs.infisical_url }}/api/v3/secrets/raw" \
        --header "Authorization: Bearer ${{ inputs.service_token }}"\
        | jq -r '.secrets[] | "\(.secretKey)=\(.secretValue)"' > ${{ inputs.output_file }}
    - shell: bash
      run: echo "Secrets stored to file /${{ inputs.output_file }}"

version: '1.0.0'
categories:
  - 'Utilities'
links:
  - name: Source Code
    url: 'https://github.com/DMJoh/infisical-action'
